### ISSUE TITLE
Network and Disk I/O are reported wrongly in csv output

### ISSUE THREAD

**Issue by pnikos** [scottchiefbaker/dool#72]
##### SUMMARY
We upgraded from dool 1.1.0 to 1.3.0 and noticed a massive increase in these 2 metrics.
Running the 2 dool versions in parallel and comparing the terminal output and the 2 produced csvs (with the --output parameter), shows that the new version multiplies with 8 the network and the disk I/O.
This cannot be correct as the terminal output is exactly the same.
Using the parameter --bytes solves the issue but shouldn't the results from 2 versions be consistent without extra parameters?

##### ISSUE TYPE

 - Bug Report

##### DOOL VERSION
1.3.0

##### OS / ENVIRONMENT
Centos 7

##### STEPS TO REPRODUCE
Execute dool -n --nocolor --output d3.dat and check d.dat
with versions 1.1.0 and 1.3.0 and compare the output files

##### EXPECTED RESULTS
If they are executed in parallel, they should be the same or at least very similar.

##### ACTUAL RESULTS
Network and Disk I/O (at least because we do not track all possibly produced metrics) are 8 times bigger than before.

**Comment by scottchiefbaker** [comment]
In version [1.3.0](https://github.com/scottchiefbaker/dool/releases/tag/v1.3.0) there was a [fix](https://github.com/scottchiefbaker/dool/commit/ebfc2ff6e03213223a4007eedd47302fd1ed1989) that corrected bits/bytes in CSV output. Prior to that version **all** data was output to CSV in bytes regardless of "bits" setting.

I believe the number you're seeing in 1.1.0 is incorrect due to this bug and was corrected in versions 1.3.0 and newer.
